### ISSUE TITLE
Failure to fetch gps altitude from exif

### ISSUE THREAD

**Issue by AndKe** [activityworkshop/GpsPrune#12]
I have thousands of photos like that, made using the same camera/camera model.
random photos will not display altitude, and so not contribute to altitude profile.
it seems very random.  exiftool , eye of gnome, shotwell - no have any trouble with the altitude in those.
also: some are actually modified using exiftool, other are stright from camera, that does not influence the chance of failure in GpsPrune. 

![img_4402](https://cloud.githubusercontent.com/assets/1468842/26402767/dd2fa174-408b-11e7-854c-1810112f2e53.JPG)

**Comment by activityworkshop** [comment]
GpsPrune tells me the altitude of that photo is 65 metres, which seems reasonable if it's so close to the sea.  What altitude did you expect?
And what do you mean that it doesn't "contribute to the altitude profile"?  Could it be that it's just the altitude profile misleading you if 65 metres is the minimum altitude of the track?

**Comment by AndKe** [comment]
funny. This is one of lots of photos, where maybe 20% do not show anything in the altitude profile (there is space between blue bars)  - I've even tested loading only that photo, and the right pane shows coordinates and no altitude.

Here is a different dataset : please observe missing altitude:
![image](https://cloud.githubusercontent.com/assets/1468842/26424930/4963cf2c-40d3-11e7-98a1-c434217bc1a8.png)

 Ubuntu 17.04 , GpsPrune 18.6, build 343  (reproduced on two different computers)

**Comment by activityworkshop** [comment]
Ok, so the problem with this image is that it does have an "Altitude" value but doesn't have a "**GpsAltitudeRef**".  Normally the GPS information in the Exif comes in 6 values: Latitude & LatitudeRef, Longitude & LongitudeRef, Altitude & AltitudeRef.  What your GpsPrune is doing is discovering that it does not find the pair (Altitude & AltitudeRef) and is therefore assuming that the point only has a valid longitude and latitude, and no valid altitude.

It's possible to add an altitude reference of "above sea level" to a single image using exiftool like this:
exiftool -gpsaltituderef=above testimage.jpg

So why did _my_ GpsPrune tell me it was 65 metres?  It turns out that the behaviours of the internal and external exif libraries are slightly different in this case.  I'm using the internal one, and it apparently doesn't care that the GpsAltitudeRef is missing, and you are using the external one, and it apparently does.

On the one hand, the specification seems fairly clear, that both Altitude and AltitudeRef are required.  So you could argue that my GpsPrune (and your other programs) are behaving wrongly by accepting an altitude without a reference.  But it's probably easier to argue that if an altitude reference is missing, you can pretty reliably guess that it's metres above sea level, in which case your GpsPrune should be changed.

I don't think this is a common issue (unless there's a popular program writing tags like this), so I don't think it needs an urgent fix.  What do you think?

**Comment by AndKe** [comment]
Hi. thanks for figuring it out, and explaining.
The full story is: the cameras tag the pictures if they have a fix, then a script fetches proper position from autopilot (based on much more precise, and corrected GPS&GLONASS) the script is replacing lat/lon+latref/lonref and altitude, but it did not write altituderef (so unless camera had a fix, there was no such tag)
I've corrected it in my scripts now, sorry for thinking that was a bug, as I only observed the fact that "altitude" was present.
