### ISSUE TITLE
GPS Week Number Rollover mitigation

### ISSUE THREAD

**Issue by SmallAndSoft** [activityworkshop/GpsPrune#30]
There are many devices affected by April 6, 2019 [rollover](https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover)
Dates are back in 2001. Need a one button +1024*7 days fix to get correct dates on points.
Please implement this low hanging but useful feature. Thanks!

**Comment by activityworkshop** [comment]
I'm happy to look at this, but I can't guarantee a "one-button" solution!
Do you think it would be enough to just extend the "Days:" field of the "Add time offset" function to allow you to type in 7168 yourself?

fperrin has already proposed an alternative solution where you can enter any integer multiple of 7168 days to add or subtract, but by the sounds of it you'd only ever want to add 7168, never subtract n*7168 days, right?  I knew that not all receivers react well to the rollover but I didn't realise that this reporting of incorrect dates was a common issue.

**Comment by SmallAndSoft** [comment]
Most common use case would be just to add 7168 days, yes. Surely there are a number of ways to present it to the user. I never heard of anyone impacted by even earlier 1999 rollover but you may wish to futureproof from the next one in 2038. Maybe a logic of pulling dates closer to the current time with 7168 days additions may do it. Subtracting does not seem necessary.

**Comment by fperrin** [comment]
I usually capture tracks with my phone and add the issue with GPSLogger, [which has now been fixed](https://github.com/mendhak/gpslogger/issues/779). I considered doing the adjustment automatically, but then the question is, how do you know if the track was captured in the last few days, or if it is indeed ~19years old? In my case the issue was fixed quickly, so I had only a few files with the issue, and I never tried to make it easier to use.

I suppose when the user opens a file with timestamps that are from >1024 weeks ago, there could be a popup saying "it looks like the trackfile you are loading is affected by the GPS week number roll-over, meaning all dates are off by approximately 19 years. Do you want to adjust timestamps from `<range of timestamp in current file>` to `<range adjusted by 1024 weeks>`?"

**Comment by SmallAndSoft** [comment]
Sound very reasonable to me @fperrin

**Comment by activityworkshop** [comment]
I don't like the idea of an annoying popup just because the file is old.

I would expect the number of devices suffering from this rollover problem will only get smaller over time as their software gets updated and patched to correct their behaviour; on the other hand the number of data files which are older than 1024 weeks (and which would therefore trigger your popup every time they're loaded) is growing every year.

In my opinion the best solution is to make it as easy as possible to add 1024 weeks for the small number of people who need to do that, _without_ adding any annoyances for the large number of people with properly-functioning receivers.  I agree that adding 7168 days is not very intuitive, but having a "Weeks" field where you can type in 1024 would for sure be better.

For those users with a bunch of such files, one way to fix all of them would be to use GPSBabel and the option "move=7168d", so that they don't have to be manually corrected one by one.

**Comment by SmallAndSoft** [comment]
The number of suffering devices will surely get smaller but not because of software update. Manufacturers are quick to abandon support for perfectly good receivers and loggers. A popup can be annoying indeed, that is why I asked for one button fix in the first post.

**Comment by activityworkshop** [comment]
An extra field for "weeks" is now in version 21, so it's much easier to enter "1024" for the value.
