### ISSUE TITLE
Add: function to calculate the distance at any point on the track.

### ISSUE THREAD

**Issue by Piskuliki0723** [activityworkshop/GpsPrune#31]
Surprisingly, this has not yet been done in software.
I can see the total track distance, I can add other parameters (speed, time, vertical speed, date, altitude).
But one of the most important functions (which is not) is the **`distance`** at any point on the track.

Example, I have gpx route distance = 78 km. I would like to move 31 km along the track. I cannot do this because there is simply no such function.

**Comment by activityworkshop** [comment]
It sounds like you're expecting the distance to be a property of the point, like the altitude or the timestamp.  It's not, it's a property of a _range_ -- any range, whether it's a range from the start of the track to this point, or from the start of the segment to this point, or from the bottom of the hill to this point.  All you have to do is select the range you're interested in and then look in the "Range details" section, not the "Point details".

In fact, you've done this already, you said you had already selected the whole track as the current range and then seen the total distance in the range details.  So just select a range from the beginning of the track to the point you're interested in.  There are several ways of doing this.

Your next question is slightly different, you'd like to know which point is 31 km from the beginning.  In this case you'd need to guess first, and select a larger range if the distance is less than 31km, or reduce the range if the distance is greater.  For this you'd probably want to first select the first point (Ctrl-Home), then shift-click another point (either on the map or on the altitude panel), then shift-click a different point depending on whether you want to make the selected range larger or shorter.

Another option would be to use the function "Track->Create marker waypoints" and use a distance limit of 31 km.  In your case you will get two markers created, one at 31 km and a second at 62 km.

I'll close this issue because I think it's resolved now, please feel free to reopen it if you have further questions.
