### ISSUE TITLE
Download SRTM Online Altitude Error

### ISSUE THREAD

**Issue by xb3b6** [activityworkshop/GpsPrune#37]
![2](https://user-images.githubusercontent.com/80679015/120783821-15d23100-c534-11eb-9e69-5cde1675c77d.jpg)

**Comment by activityworkshop** [comment]
You're right.  Unfortunately usgs.gov don't supply those files any more.  Please upgrade to GpsPrune 20.3 or 20.4, which now use a different server.

**Comment by xb3b6** [comment]
@activityworkshop 
This error (screen) from version **20.4 for Windows**

**Comment by activityworkshop** [comment]
I don't think that screenshot _can_ be from GpsPrune 20.4, because that version doesn't use usgs.gov any more.  It's easy to check the version number, just go to "Help -> About GpsPrune" or "Help -> Check for new version" to see which version you're using.

Maybe you downloaded 20.4 but you're still running a previous version?

**Comment by xb3b6** [comment]
![git](https://user-images.githubusercontent.com/80679015/120891815-4937bd00-c613-11eb-8f90-18cbe993f554.jpg)

**Comment by activityworkshop** [comment]
Well, as you can see that's a _different_ error message, it's not from usgs.gov, it's from kurviger.de.  So when you use 20.4 it does indeed use the correct server and no longer usgs.gov.

It's also doesn't say "FileNotFound" like your previous screenshot, the server is now returning 403 (forbidden), so that's a different error.  The URL works fine for me though, so I don't know exactly what your problem is.  Do you get a better error message when you go to that URL with your browser?  Or if it works, then just save the zip file in the `srtm` folder of your cache.
