### ISSUE TITLE
Map not correctly centered and zoomed when started from terminal/filemanager

### ISSUE THREAD

**Issue by gueba** [activityworkshop/GpsPrune#43]
Hi there,
I'm on Xubuntu 20.04 and experienced a strange (buggy) behaviour since version 20.1 of gpsprune. 
I use to watch my tracks by double-clicking on it in the filemanager or by starting gpsprune with the desired track from terminal.

Up to version 20.0 this worked fine - the map zoomlevel was set correctly and the map centered to show the whole track.
From version 20.1 to 20.4 - if "prune.showmap=1" is set in the ".pruneconfig" the map is mostly set to the zoomlevel of the last opened view (track is not shown completely or too small - not centered). Closing gpsprune and re-opening succeeds in a correct view.
Edited: Setting "prune.showmap=0" seems to correctly zoom and center the map, but of course no map is shown.

I guess, that the feature that came with 20.1"Starting GpsPrune with a map view, rather than an empty window (thanks to fperrin)" is responsible for this behaviour.

Unfortunately I have no possibility to test on other OS at the moment.

Any help is appreciated

**Comment by activityworkshop** [comment]
Hi, and thanks for the clear problem description.
I agree with your guess that it's because of the initial map view, and because the last-viewed area of the map is now remembered at exit and re-applied at startup.  If you start GpsPrune without a data file this is a big improvement I think, but it seems you have identified some less-than-ideal side effects when it's started _with_ a data file (or files).  It will most likely depend on the location of the loaded file compared to the last-viewed area too.

I will have to look at the behaviour in more detail, but my first guess is that doing a "zoom to full scale" at the appropriate part of the startup sequence should fix things for you.  Unfortunately this won't make it into Version 21 which is just being waxed and polished, but it sounds very fixable for Version 21.1.  Until then I recommend you just do the "zoom to full scale" yourself after startup.

**Comment by gueba** [comment]
Thank you for the quick response.
Waiting for version 21 is no problem for me as the "zoom to full scale"-function works well (I didn't have that in mind). Doing this at startup would even be more comfortable though.

Many thanks for your efforts - you're doing a pretty good job.

**Comment by fperrin** [comment]
Hi @gueba & @activityworkshop,

I seem to remember I had that issue when playing around with displaying the map at start up. It was an intermittent issue, possibly a race between loading data and setting up the GUI? Those are done in separate threads. Looking at the history, one thing I did, but that hasn't been integrated in GpsPrune, was a call to `_mapCanvas.zoomToFit()` in `tim.prune.App.informDataLoaded()`, just after the call to `_menuManager.informFileLoaded`. See https://github.com/fperrin/GpsPrune/commit/e215e7b4f3dc812aefac3f8faf4a1b4df7f15075#diff-4b7a12d0e90c5f2b3721b889b803f5674ec4a248ea07261ca061131bb8b73ff1R762

I don't presume that the above is the right thing to do, Tim you know GpsPrune better than I, so I assume you had a good reason?

**Comment by activityworkshop** [comment]
I'm not aware of any race conditions in the data loading, and I haven't noticed any "intermittent" issues myself.
The current behaviour is not _always_ to zoom to fit when loading a new file (whether loaded at startup or loaded from the regular "open file" command).  So that would be a change in behaviour, I'm not sure whether that's always what one expects to happen when loading a file (especially when loading an _additional_ file).

**Comment by activityworkshop** [comment]
I think this is resolved now with 21.1.
Please correct me if I'm wrong, and feel free to re-open this issue if it's still not working the way you expect.

**Comment by gueba** [comment]
Works very well at first glance. Thank you very much!
