### ISSUE TITLE
Information about the date(s) of the track.

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#48]
View -> details. The track information is displayed, but the date (day, month, year) is missing. Because of this, you have to use other tools.
It is difficult to name such instruments that do not display the date of the track.
GPSprune v21.2

**Comment by activityworkshop** [comment]
You're asking about the date of a track, but let's talk about the date of a point first.  If you select a single point (either a track point or a waypoint) then you can see its date (if it has one) in the "Point details" panel on the right.  If you go to View -> Full details then the date is also shown on the "Point details" tab of the popup dialog.

Now for a selected _range_, there might be zero or one or more dates present, so it's not possible to always show a _single_ date.  Maybe you're expecting it to show a range of dates?  Or to show a single date but only if all of the points in the selected range share the same calendar date?

For the whole track it's a similar problem - in general there's zero or more dates present.  So in the special case where every single point has the same date then the date of the track could be shown, but not in the point details or the range details, are you expecting it to be in the "Track details" in the top left?

If you want to know which dates are covered by the track, the easiest way is to open the dialog "Track -> Delete points by date" and it will show a list of dates and the number of points recorded on each date.  Unfortunately this doesn't show anything useful if all the dates are identical, because then there's nothing to delete, but then in that case you can just select any point in the track and look at its date.

I'm afraid I don't understand what you mean about naming instruments.

So, feel free to make a proposal, do you want to see the date range of the current selection in the "Range details" panel, or do you want to see the date range of the track in the "Track details" panel?  And what do you expect to see if the range or track includes also points without any time information?

**Comment by snooppr** [comment]
When opening a track (one) there is no information about the date, it is logical to select the track with the key combination: "Ctrl + A". And when the track is selected, the panel displays all the information about the track except the date, when you enter the menu, there is also no date. It turned out that you need to select any one point on the track and the date will be displayed, It's really confusing, but it works, thanks I close the question.

**Comment by activityworkshop** [comment]
> no information about the date

Again, you're talking about **the date**.  What I was trying to explain is that in any track there might be no date, there might be a single date, or there might be several dates.
But if you want to close the question, that's also fine.
