### ISSUE TITLE
3d. The .pov file is generated with "errors" if there are water objects near the track (rivers, swamps, etc.).

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#54]
Example. Here is the track I generated in graphoper (the [archive](https://disk.yandex.ru/d/BtWVO9etrPeYyw) contains the track and generated data for povray).

This is what (nice) 3d looks like (java3d)
![3d](https://user-images.githubusercontent.com/61022210/174769199-c38ebbf4-b421-410e-8318-d72cd9702910.png)

This is how the same track looks in povray (raised the resolution a bit, chaotic water pixelation)
![1test cleaned](https://user-images.githubusercontent.com/61022210/174769274-abdd8ce3-92c2-47f9-8c8f-bd2241d10529.png)

`$ povray '~/home/1test.pov' +W3800 +H3800`

Export options.
![export](https://user-images.githubusercontent.com/61022210/174768139-dfe94de7-bd77-4619-bd81-7e09cadf55b1.png)

You can see chaotic multiple blue and blue pixels spaced all over the map from the water (where there is no water).
![3d pov cleaned](https://user-images.githubusercontent.com/61022210/174770365-61d5b234-c78c-4c1b-8b22-893f86223d9d.png)

I thought maybe it was the version of povray (using povray and gpsprune on linux), but another version of povray on Android (termux) gave the same unfortunate result with chaotic water pixelation.
Yes, I played around with height factors, grid and camera position, but the problem is not completely solved, this is a bug that deserves attention.

**Comment by activityworkshop** [comment]
Thanks, that's another good bug description. This one is all GpsPrune's fault, but it's got nothing to do with water.

The problem here is that the landscape in this area is ridiculously flat, which isn't typical for most of the landscapes used during testing. The surface with the map image is then right in the same place as the base box, and this makes the rendering really difficult. So Povray gets confused about which of the two is visible, and this produces the unfortunate artefacts. But it's completely unrelated to rivers or swamps.

The short term solution is to edit by hand the `.pov` file and remove the lines which define the `box` (just after the comment "Base plane").

The bug fix will come with GpsPrune version 22. Thanks again.

**Comment by activityworkshop** [comment]
fixed :)
