### ISSUE TITLE
How to insert a new trackpoint before/after the currently marked?

### ISSUE THREAD

**Issue by pstein** [activityworkshop/GpsPrune#59]
How can I insert manually a new trackpoint before/after the currently marked?

**Comment by activityworkshop** [comment]
The easiest way is to grab the midpoint between two track points (assuming that they're in the same segment) and drag it to create a new point.  For this, the edit mode has to be on (see the toggle switch at the top-middle of the map) or the AltGr key has to be pressed - this restriction is so that points aren't dragged to new positions accidentally when all you want to do is drag the map around.

**Comment by activityworkshop** [comment]
I presume this can be closed too.
