### ISSUE TITLE
Split into segments at current point

### ISSUE THREAD

**Issue by jareware** [activityworkshop/GpsPrune#6]
It would be amazing to be able to split the track into segments at the currently selected point.

Furthermore, adding names to these segments would be even more amazing, but one thing at a time. :)

Thanks for your great work!

**Comment by activityworkshop** [comment]
There are a few ways to split a track into segments, either automatically (based on distance / time with the "Track -> Split track into segments" command) or manually.  The manual ways consist of modifying a range, so that the selected range is one segment, or modifying a point, so that the selected point becomes the beginning of a new segment.

For example, if your track has only one segment of ten points, and you select a current range containing points 5 to 9 inclusive, and then select "Range -> Merge track segments", then the result will be three segments - (1-4), (5-9), (10).
If you now select the range 3 to 10 inclusive, and do "Range -> Merge track segments" again, you'll get two ranges, (1-2) and (3-10) because the segment breaks at 5 and 10 will be removed by the segment merge.

The point method uses the operation "Point -> Edit point" on the currently selected point.  In the resulting table you can find the field called "Segment" and change its value to 1 (to make this point the beginning of a new segment) or 0 (to make it part of the previous segment).

I suppose there is room for improving this, to make it more obvious or to reduce the number of clicks.  Perhaps a menu command or a toolbar button?

As to your second question about naming the segments, that's a little more difficult to implement, because there are lots of cases where the names would have to be automatically modified, like editing/deleting points, deleting/reversing ranges, cut&move range and so on.  I'm open to suggestions how this could be managed, but I think there are a few complex issues to solve.

**Comment by jareware** [comment]
Oh, got it, thanks for the thorough answer!
