### ISSUE TITLE
How to switch really automatically to a thin, red trackline?

### ISSUE THREAD

**Issue by pstein** [activityworkshop/GpsPrune#61]
In menu Settings--->Set Color I clicked on color red 
and in menu Settings--->Set display options I set thickness of lines to 1
Afterwards I saved the settings

Now I drag a *.gpx file onto GPSprune window and it is shown in map but with a fat blue line.

Why?

Restart GPSPrune does not help.

When I click on the tiny icon labelled "Connect track points" on top of the map the thickness is reduced but not the color.

Why?

**Comment by activityworkshop** [comment]
I suspect that you're using a "point colourer" (Settings -> Set colours).
If you're using a point colourer, then the colour of the track points will come from the colourer you chose, and not from the colour patch "Points".  Just set your colourer to "None" and then you should immediately see your chosen colour (even before you save settings or restart).

When you click the "connect track points" icon you switch off the drawing of the track points and just show the lines between the points, that's why the line thickness looks reduced (zoom in to see).

**Comment by pstein** [comment]
Sorry, I am confused by your answer.

I clicked on menu 

Settings--->Set colours

Then on red color 
Colourerer type=None
No "line" entry can be found in drop down
Finally I click on button "OK".

The track line on map remain blue.

What more can I do?

**Comment by activityworkshop** [comment]
Ok, in that case my suspicion was incorrect ;)
In that case, my _suspicion_ is that you're not changing the colour of the colour patch "Points".  The colour of "Points" is used both for the points and the lines between them, and also for the altitude diagram, as you can easily see by playing around with the colours yourself.  Perhaps you're changing the colour of the patch "Lines", which affects the horizontal lines on the altitude diagram:
![colours](https://user-images.githubusercontent.com/11003522/189406098-2f65b60e-f18d-493e-b962-f4d26f858c44.png)

**Comment by pstein** [comment]
Ok, works

**Comment by activityworkshop** [comment]
You're welcome.
