### ISSUE TITLE
Shape scale factor has only two track scales, but you can manually set anything.

### ISSUE THREAD

**Issue by snooppr** [activityworkshop/GpsPrune#62]
![5 cleaned](https://user-images.githubusercontent.com/61022210/190953403-88c7cf61-d209-4a6f-9050-04aa5f87221a.png)

Shape scale factor has only two real values (any number less than 1 and any number greater than 1). And you can manually set any numbers, as in other fields, and this confuses. It is better to set the **switch** "small/large" GpsPrune. Better yet, add something in between, like 0; 0.5; 1.

![0](https://user-images.githubusercontent.com/61022210/190953781-4094e78c-b77a-47ee-b543-21501fbf2155.jpg)
">"1 - too large, "<" 1 - small

**Comment by activityworkshop** [comment]
For me it's **not** true that only two real values are available - I can scale anywhere between 0.1 and 2.0.

![3d-shape-scaling](https://user-images.githubusercontent.com/11003522/191068161-60c4fbd4-29b0-41c7-8e7d-b35b3039f661.jpg)

What exactly are you typing into the field, are you using "0.5" or "0,5" or something else?  You should definitely see a difference between "1" and "2", but maybe it's a decimal point problem with your locale?

Your value of "666" doesn't make sense (the shapes would each be larger than the whole map) so the value is capped at 2.0.

Some improvements I can suggest:
 * the capped value should be entered back into the edit field so that you know it's been capped at 2.0
 * possibly a factor up to 3.0 should be allowed, but the main point of the function is to //reduce// the size of the shapes.

**Comment by snooppr** [comment]
`locale -k LC_NUMERIC`
_decimal_point=","
thousands_sep=" "
grouping=3;3
numeric-decimal-point-wc=44
numeric-thousands-sep-wc=8239
numeric-codeset="UTF-8"_

![000](https://user-images.githubusercontent.com/61022210/191414537-3d20c56f-319f-47e1-a749-55dd1f9ba082.png)

I set the fractional sign through [,]. 
[.] is not available.
Probably, GpsPrune needs to choose a fractional sign not forcibly, but taking into account the user's locale.

**Comment by activityworkshop** [comment]
I would expect "0.4" to work in those locales where the decimal point is a `.` and for "0,4" to work in those locales where the decimal point is a `,`.  I will need to experiment to see why this isn't working for you.

**Comment by activityworkshop** [comment]
Ok, I can see what's going on now and I have a way to fix it.
Thanks to both @snooppr and @jannis701 for reporting and describing the problem, it's greatly appreciated.  I'm annoyed that I didn't find it myself though ;)
I'll prepare a 22.2 with the fix, so I'd be grateful if you could have a look at that when it's ready.

**Comment by snooppr** [comment]
I confirm, in GpsPrune v22.2 (401) deb The problem is solved.
Thank you.
