### ISSUE TITLE
Easier remove of connected photos from selected point range

### ISSUE THREAD

**Issue by romanlinhard** [activityworkshop/GpsPrune#66]
I would prefer if you extend "Delete field values" action with the possibliity to remove all LINKS from a selected range of points/track points. 
As you can see in the example below, I can already remove elevation, time & name from that point (if he is selected in a range of track points), but I miss the LINK field here.
Currently thats only possible via single selection of points and track points, not for a selected range of points.

Bye
Roman

**Comment by romanlinhard** [comment]
As Github scrub my GPX example from my post, I will deliver an example (if needed) via other ways.
Sorry.
![Screenshot_2023-02-19_12-41-10](https://user-images.githubusercontent.com/23191682/219945700-2e3f544a-196d-45f9-83dd-76211b0987e7.png)

**Comment by activityworkshop** [comment]
Hi, and thanks for the suggestion.
The photo and/or audio for each point aren't stored in quite the same way as the other fields, so that's why they don't appear in the list.

But you're right, that would make sense if they were available there too.  Currently as you say it's easy to unlink a single photo (either disconnect or remove from the menu), and it's easy to unlink _all_ the photos (just export as gpx without photo points).  But to just unlink the photos or audios from the selected range would be much easier with your suggestion.

**Comment by romanlinhard** [comment]
Hi, 
yes, let's think about, what makes the "work" with GPSPrune easy and efficient.

**Comment by activityworkshop** [comment]
You can try this out with the _test_ version of 23 if you like (see the development page).  Bugs are still being found though!

**Comment by romanlinhard** [comment]
Hi GpsPrune team, 
I tested the feature in test version 23 and it works as expected. Great job!
Btw: Nice looking new Icons ...

Bye Roman

**Comment by activityworkshop** [comment]
done :)  and thanks!
