### ISSUE TITLE
Two requests (<sym>, track points list)

### ISSUE THREAD

**Issue by BP22190** [activityworkshop/GpsPrune#72]
Hello,

I would like to suggest two improvments:

- possibility to edit the <sym> </sym> value for a waypoint;
- possibility to show the track points list, and better, possibility to delete points from this list.

Best regards,

**Comment by activityworkshop** [comment]
Your first request sounds like wishlist item number 72 "Support additional fields like gpx's cmt, sym and hdop".  I can't think of what GpsPrune could usefully do with the contents of the `sym` tag, at least GpsPrune isn't able to show a corresponding symbol (there is some discussion about that under Issue #3 ).  However, if you load a gpx file with sym tags, and delete points, rearrange points etc and then export as gpx again, the sym tags will be retained in the saved file.

To _edit_ the sym value would require GpsPrune to actually read it and store it, and show it in the "Edit point" dialog.  That would be possible, if it were useful (for me I don't think it's particularly useful because I don't use those symbols much).

The second one sounds like Issue #60 "How to view the trackpoint list for a dragged *.gpx file?" - if you have any additional explanations for that one, you can add them either here or there :)

**Comment by BP22190** [comment]
_"if it were useful (for me I don't think it's particularly useful because I don't use those symbols much)."_

For me, it's not to be used directly in gpsprune, but it would be useful for editing gpx files for particular website that uses these tags.

**Comment by activityworkshop** [comment]
Adding support for editing the `sym` tag seems to be fairly straightforward so it should be no problem to include in version 23 when it's ready.

**Comment by activityworkshop** [comment]
the first part is done, the second part is the same as Issue #60  I believe, so it can be discussed further there.
