### ISSUE TITLE
Gpsprune doesn't render terrain in the Three-D mode. Base image option is set to "no" and grayed out

### ISSUE THREAD

**Issue by Alekssavin** [activityworkshop/GpsPrune#83]
Hi.
I seem to have trouble with rendering terrain in the Three-D mode.
When I try to do it, in the "Three-D view" window the parameter Base image is set to "no" and the "Edit" button is grayed out, so I can't change it as they do in many online tutorials.

After that, when I ignore it and proceed I see the warning about SRTM data missing (I assume it's because I record tracks just over the 60°N). However, my track contains altitude information recorded by my GPS device. In the end I get my track with correct altitude profile displayed in the Three-d mode, but the terrain is not rendered.

I tried doing the same with another track recorded on the southern side of the 60° parallel. I got no SRTM warning. But in the end the same result: the terrain is not rendered.

I have `gpsprune` installed on my `Opensuse 15.4` from its official repositories.

**Comment by activityworkshop** [comment]
I'll copy my email answer to a recent question here, because it's almost exactly the same as yours:

> When I run 3D view, the "base image" option says "no" and the "edit" button is inactive, so I cannot change it.

The base image for the 3d views use the map images from your tile cache.  If the "Edit" button is inactive, this means that it cannot find any images in your cache.  If you don't have a tile cache, I recommend you set this up with Settings -> Save maps to disk.
You should see some messages to this effect every time you run GpsPrune, recommending that you save the images locally:
    > By setting up a disk cache (Settings -> Save maps to disk)
    > you can speed up the display and reduce network traffic.

You should also save your settings so that GpsPrune can always find the cache you specified.

North of 60 degrees the SRTM data won't be available, and that means no terrain rendering.  But if you can find alternative altitude data and save this in your cache, then you should be able to render terrains from that.

**Comment by Alekssavin** [comment]
Oh, great, thanks! It worked for the track recorded south of 60N.
There is no data for north of 60N for the terrain so far unfortunately, as you mentioned [here](https://github.com/activityworkshop/GpsPrune/issues/53). Maybe one day it will be possible with the same sources OsmAnd pulls its data from.
