### ISSUE TITLE
Opening of Garmin Archive-files in version 23

### ISSUE THREAD

**Issue by gueba** [activityworkshop/GpsPrune#87]
My Garmin nuevi devices store latest data in 'Current.gpx' - file, older data in Archive - files '123.gpx' ...
These files consist of waypoints and several tracks (with tracksegments).
Opening such file with older versions of gpsprune (up to 22.1) I was offered a window, where I could select, which track(s) to open. This does not work in version 23.x. gpsprune23 opens all tracks at once, so I have to manually delete all the unwanted tracks.
Could the old behaviour be implemented again, I found it very useful.

![open-dialogue](https://github.com/activityworkshop/GpsPrune/assets/65403097/14b239fb-204f-467f-8299-da41d52ed386)

**Comment by activityworkshop** [comment]
You're correct, this dialog no longer appears with version 23, sorry.

I mentioned this briefly in the "what's new" page:

> There were a couple of casualties of this upheaval though. ... a second was the "select tracks" dialog which came up when loading a gpx file containing multiple named tracks. This was originally introduced because it was something I often wanted to do (due to receiver hardware behaviour); I haven't used it for a long time so I'm guessing (hoping) that others don't either.

I also mention this disappearance in the user guide, and in there I suggest that you might be able to get a similar effect either by using the "delete points by date" function, or the "delete points inside a rectangle" function, or some combination.  If you only want the last segment you can select the last point, then select the current range and then do Range -> Crop track.  There are many other ways to do it too.

I don't have a use for this list any more but it sounds like you do.  If it transpires that it's still wanted / needed, then I can think about how it could be re-introduced using the new system.

**Comment by gueba** [comment]
Thank you for clarification. I didn't RTFM. My bad!

Please don't spend time and work for this detail, as it seems to only affect me. I will feel ok with the workaround (only will have to change my workflow lightly).

Thank you again for a good job!

**Comment by activityworkshop** [comment]
> My bad!

Not at all, it's great that you're giving feedback like this - otherwise I don't know which features are being used.  I know that as a user it's frustrating when something which used to work suddenly stops working with the next release.  In this case the need came from a change to the way the commands are executed, and the motivation to keep things as consistent as possible. At the time it just wasn't obvious how to adapt the loading mechanism around this new setup, so it was easier to make a single command for all the loading options, regardless of whether it was gpx, kmz, csv or whatever.

It would of course be _possible_ to re-introduce this additional dialog by adapting the command to cope with it, but as I wrote, I haven't used it for a long time and the other options (deleting by date, deleting by rectangle, selecting a segment and deleting the range) work in the same way for _any_ kind of data, no matter where they were loaded from, and at any time not just load time.

Please try out using those other functions and let me know what you think - one option would be to re-introduce this selection dialog (but only when loading gpx / gpx.gz), another option would be a separate one to "delete by segment" but that's more similar to the existing "delete by date" function, so probably not so useful.  A third option would be to load and store each track separately, and then have a "delete by track" function, but that would change GpsPrune's model quite a bit and make it maybe less straightforward to use?

**Comment by gueba** [comment]
I just tried out the 'delete by date'-function and it works like a charm. This makes the preselection unnecessary. In fact it is better, because you can see the loaded track(s) on the map, which may help chosing. So everything is fine on my side.
:+1:

**Comment by activityworkshop** [comment]
In that case I'll close this issue (for now).  Thanks for your feedback!
