### ISSUE TITLE
Make it easier to copy node info

### ISSUE THREAD

**Issue by DFyson** [activityworkshop/GpsPrune#9]
It would be nice if it were easier/faster to copy information about a node such as the date, coordinates, etc. Currently I have to go point → edit point then selected the value, highlight it and copy it. What would be nice is if that could be done more smoothly. I could imagine having buttons next to the values so they can be copy-pasted. Same goes for range details such as distance, duration, average speed, etc.

Or better yet, Ctrl-C on a node will copy that nodes details in a multi-line format so it can be pasted into a spreadsheet. And copy the range details for a selection of nodes.

**Comment by activityworkshop** [comment]
Ah, you mean a button for each field in the edit point dialog?  That could be an option but might look quite ugly I think.
Ctrl-C is currently the shortcut for "Compress track", because copying and pasting points isn't possible.  Copying the current point to a multi-line string would work but I wouldn't put that on Ctrl-C because you'd never know whether you were copying the current point or the currently selected range.  Plus, if you copy all the fields of a point at once, you'd never know which fields you were going to get or in what order.  Points might contain _anything_ depending on where they come from.

The "full range details" dialog could contain options to copy values, because they're defined by the dialog.  Only the presence or absence of altitude information and timestamp information in the track determine which fields can be calculated and which not.

**Comment by DFyson** [comment]
I was thinking on the main screen, maybe have small unobtrusive button next to each field, or have the fields selectable so you can highlight and copy. In the node edit window I don't really see a point of having individual copy buttons since at that point you can just highlight the field and copy. Maybe a 'copy all' button?  I'm just trying to find a way to make it faster to tabulate a bunch of specific nodes per gpx file into a spreadsheet. So for example looking at a map of places I've been then I might want the coordinates and time. Or select a range to figure out how long it took me to get from A to B.

I see what you mean that copying the raw node data could be inconsistent between gpx files. So ya it would need to be parsed first. Then maybe if there was a button to copy all the fields in the node edit window, make a keyboard shortcut which just calls that but without opening the window?

**Comment by activityworkshop** [comment]
You can now copy point or range details from the "View -> Full details" panel, so for many purposes this issue is fixed now I think.
If you want to copy a large number of point details into a spreadsheet then the best way would be to save the whole track as a csv and just load it into the spreadsheet from there.
Feel free to re-open this issue if there's something else missing.
